plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-parcelize'
    id 'com.google.devtools.ksp'
}

android {
    namespace 'com.dl.m3u8recorder'
    compileSdk 35

    defaultConfig {
        applicationId "com.dl.m3u8recorder"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildFeatures {
        compose true
    }

    composeOptions {
        kotlinCompilerExtensionVersion '1.5.10' // 🚀 【关键修复】将 Compose 编译器版本与 Kotlin 1.9.22 匹配
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }

    lint {
        disable 'NullSafeMutableLiveData'
    }

    packagingOptions {
        resources {
            excludes += ['META-INF/*']
        }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.7.0'
    implementation 'androidx.activity:activity-compose:1.9.0'

    // ✅ Compose Material3
    implementation 'androidx.compose.material3:material3:1.2.1'
    implementation 'androidx.compose.ui:ui:1.6.7'
    implementation 'androidx.compose.ui:ui-tooling-preview:1.6.7'
    implementation 'androidx.navigation:navigation-runtime-android:2.9.2'
    implementation 'androidx.navigation:navigation-compose-android:2.9.2'

    // 🚀 【重要修改】只保留 Media3 (新的 ExoPlayer) 依赖
    implementation 'androidx.media3:media3-exoplayer:1.8.0'
    implementation 'androidx.media3:media3-ui:1.8.0'
    implementation "androidx.room:room-runtime:2.6.1"
    ksp 'androidx.room:room-compiler:2.6.1'
    implementation "androidx.room:room-ktx:2.6.1"



    debugImplementation 'androidx.compose.ui:ui-tooling:1.6.7'

    // ✅ 协程
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
    implementation "com.google.accompanist:accompanist-flowlayout:0.34.0"

    // ✅ XML 样式资源支持（Material Components 2）
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'com.moizhassan.ffmpeg:ffmpeg-kit-16kb:6.1.1'
}
